---
- name: Create users from a file
  hosts: windows
  gather_facts: no
  vars:
    user_file: "C:\\Temp\\users.txt"  # Zielpfad auf dem Windows-System

  tasks:
    - name: Ensure the Temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Copy the user file to the Windows host
      win_copy:
        src: files/users.txt
        dest: "{{ user_file }}"

    - name: Read and parse the user file
      win_shell: |
        Get-Content "{{ user_file }}" | ForEach-Object {
          $parts = $_ -split ':'
          [PSCustomObject]@{
            Name = $parts[0]
            Password = $parts[1]
            Group = $parts[2]
          }
        } | ConvertTo-Json -Depth 1
      register: user_data

    - name: Create users from parsed data
      win_user:
        name: "{{ item.Name }}"
        password: "{{ item.Password }}"
        groups: "{{ item.Group }}"
        state: present
      with_items: "{{ user_data.stdout | from_json }}"
