---
- name: Create users from a file
  hosts: windows
  gather_facts: no
  tasks:
    - name: Read the user file
      win_shell: |
        Get-Content {{ user_file }}
      register: user_data

    - name: Parse and create users
      win_user:
        name: "{{ item.0 }}"
        password: "{{ item.1 }}"
        groups: "{{ item[2] | default('Users') }}"
        state: present
      with_items: "{{ user_data.stdout_lines | map('split', ':') }}"
