---
# Play 1: System Status Dashboard auf Linux aktualisieren
- name: System Status Dashboard auf Linux aktualisieren
  hosts: linux
  gather_facts: yes
  become: true
  vars:
    dest_path: "/var/www/html/system_status.html"
  tasks:
    - name: Sicherstellen, dass Apache installiert ist
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Dashboard HTML mittels Template generieren (Linux)
      template:
        src: templates/welcome_linux.html.j2
        dest: "{{ dest_path }}"
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

# Play 2: System Status Dashboard auf Windows-Clients aktualisieren
- name: System Status Dashboard auf Windows-Clients aktualisieren
  hosts: windows
  gather_facts: yes
  vars:
    dest_path: "C:\\inetpub\\wwwroot\\system_status.html"
  tasks:
    - name: Sicherstellen, dass der Zielordner existiert
      ansible.windows.win_file:
        path: "C:\\inetpub\\wwwroot"
        state: directory

    - name: Dashboard HTML mittels Template generieren (Windows)
      ansible.windows.win_template:
        src: templates/welcome_windows.html.j2
        dest: "{{ dest_path }}"
