---
- name: Install specific applications on Linux
  hosts: linux
  become: yes
  tasks:
    - name: Test connectivity to Linux machine
      ping:

    - name: Install Flatpak (Debian-based systems)
      apt:
        name: flatpak
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Flatpak (RedHat-based systems)
      yum:
        name: flatpak
        state: present
      when: ansible_os_family in ['RedHat', 'CentOS', 'Fedora']

    - name: Add Flathub repository
      shell: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Visual Studio Code via Flatpak
      shell: |
        flatpak install -y flathub com.visualstudio.code
      args:
        warn: false

    - name: Install VLC Media Player via Flatpak
      shell: |
        flatpak install -y flathub org.videolan.VLC
      args:
        warn: false

    - name: Install Skype via Flatpak
      shell: |
        flatpak install -y flathub com.skype.Client
      args:
        warn: false

    - name: Output success message
      debug:
        msg: "All specified applications have been successfully installed via Flatpak."
