---
- name: Install specific applications on Linux
  hosts: linux
  become: yes
  tasks:
    - name: Test connectivity to Linux machine
      ping:

    - name: Update package lists (Debian-based systems)
      apt:
        update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Update package lists (RedHat-based systems)
      yum:
        name: "*"
        state: latest
      when: ansible_distribution in ['RedHat', 'CentOS', 'Fedora']

    - name: Install Google Chrome (Debian-based)
      apt:
        name: google-chrome-stable
        state: present
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Install Visual Studio Code (Debian-based)
      apt:
        name: code
        state: present
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Install Google Chrome (RedHat-based)
      yum:
        name: google-chrome-stable
        state: present
      when: ansible_distribution in ['RedHat', 'CentOS', 'Fedora']

    - name: Install Visual Studio Code (RedHat-based)
      yum:
        name: code
        state: present
      when: ansible_distribution in ['RedHat', 'CentOS', 'Fedora']

    - name: Install additional tools using Snap (if available)
      snap:
        name: "{{ item }}"
      loop:
        - vlc
        - gimp
        - slack
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Install additional tools using Snap (if available)
      snap:
        name: "{{ item }}"
      loop:
        - vlc
        - gimp
        - slack
      when: ansible_distribution in ['RedHat', 'CentOS', 'Fedora']

    - name: Verify Git installation
      command: git --version
      register: git_version

    - name: Output Git version
      debug:
        msg: "Git version installed: {{ git_version.stdout }}"

    - name: Output success message
      debug:
        msg: "All specified applications have been successfully installed."
