---
- name: Install specific applications on Linux
  hosts: linux
  become: yes
  tasks:
    - name: Test connectivity to Linux machine
      ping:

    - name: Update package lists (Debian-based systems)
      apt:
        update_cache: yes
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Update package lists (RedHat-based systems)
      yum:
        name: "*"
        state: latest
      when: ansible_distribution in ['RedHat', 'CentOS', 'Fedora']

    - name: Install Snap applications
  hosts: all
  tasks:
    - name: Install Google Chrome
      snap:
        name: google-chrome
        state: present

    - name: Install Visual Studio Code
      snap:
        name: code
        state: present

    - name: Install VLC Media Player
      snap:
        name: vlc
        state: present

    - name: Install Skype
      snap:
        name: skype
        state: present

    - name: Output success message
      debug:
        msg: "Snap applications have been successfully installed."


    - name: Output success message
      debug:
        msg: "All specified applications have been successfully installed."
