---
- name: Konfiguriere Restic auf Windows
  hosts: windows
  collections:
    - community.crypto
  tasks:
    - name: Erstelle den .ssh-Ordner, falls nicht vorhanden
      ansible.builtin.file:
        path: "C:/Benutzer/{{ ansible_user }}/.ssh"
        state: directory
        mode: '0700'

    - name: Generiere ein SSH-Schlüsselpaar mit PowerShell
      win_shell: |
        if (-not (Test-Path "C:/Benutzer/{{ ansible_user }}/.ssh/id_ed25519")) {
          New-Item -Path "C:/Benutzer/{{ ansible_user }}/.ssh/id_ed25519" -ItemType File -Force
          ssh-keygen -t ed25519 -f "C:/Benutzer/{{ ansible_user }}/.ssh/id_ed25519" -N ""
        }
      args:
        creates: "C:/Benutzer/{{ ansible_user }}/.ssh/id_ed25519"

    - name: Kopiere den öffentlichen Schlüssel zum Backup-Server
      win_shell: |
        type C:\Benutzer\{{ ansible_user }}\.ssh\id_ed25519.pub | ssh rbackup@192.168.100.137 "cat >> /home/rbackup/.ssh/authorized_keys"
      args:
        creates: /home/rbackup/.ssh/authorized_keys

    - name: Setze Umgebungsvariable für Restic Passwort
      win_environment:
        name: RESTIC_PASSWORD
        value: "kali"

    - name: Initialisiere das Backup-Repository
      win_shell: |
        restic -r sftp:rbackup@192.168.100.137:/windows init
      environment:
        RESTIC_PASSWORD: "kali"

    - name: Führe ein Test-Backup durch
      win_shell: |
        restic -r sftp:rbackup@192.168.100.137:/windows backup C:\ --use-fs-snapshot
      environment:
        RESTIC_PASSWORD: "kali"

