---
- name: Full System Backup with Restic
  hosts: all
  gather_facts: no
  vars:
    restic_repo: "/backups/restic-repo"
    restic_password: "dein_sicheres_passwort"  # Ersetze dies durch dein Restic-Repository-Passwort
  tasks:
    # Restic auf Windows installieren
    - name: Install Restic on Windows
      win_chocolatey:
        name: restic
        state: present
      when: "'windows' in group_names"

    # Restic auf Kali Linux installieren
    - name: Install Restic on Kali Linux
      apt:
        name: restic
        state: present
      when: "'kali' in group_names"

    # Backup für Windows erstellen
    - name: Create Windows system backup with Restic
      win_command: |
        restic -r "\\ubuntu-server\backups\restic-repo" backup C:\ --password "{{ restic_password }}"
      when: "'windows' in group_names"

    # Backup für Kali Linux erstellen
    - name: Create Kali Linux system backup with Restic
      command: |
        restic -r /backups/restic-repo backup / --password "{{ restic_password }}"
      when: "'kali' in group_names"