---
- name: Konfiguriere Restic auf Windows
  hosts: windows
  collections:
    - community.crypto
  tasks:
    - name: Erstelle den .ssh-Ordner, falls nicht vorhanden
      ansible.builtin.file:
        path: "C:/Benutzer/{{ ansible_user }}/.ssh"
        state: directory
        mode: '0700'

    - name: Generiere ein SSH-Schlüsselpaar mit PowerShell
      win_shell: |
        if (-not (Test-Path "C:/Benutzer/{{ ansible_user }}/.ssh/id_ed25519")) {
          ssh-keygen -t ed25519 -f "C:/Benutzer/{{ ansible_user }}/.ssh/id_ed25519" -N ""
        }
      args:
        creates: "C:/Benutzer/{{ ansible_user }}/.ssh/id_ed25519"

    - name: Kopiere den öffentlichen Schlüssel zum Backup-Server
      win_shell: |
        $publicKey = Get-Content -Path "C:/Benutzer/{{ ansible_user }}/.ssh/id_ed25519.pub"
        ssh {{ backup_user }}@{{ ansible_host }} "echo $publicKey >> ~/.ssh/authorized_keys"
      vars:
        backup_user: rbackup
      args:
        creates: "/home/{{ backup_user }}/.ssh/authorized_keys"

    - name: Setze Umgebungsvariable für Restic Passwort
      win_environment:
        name: RESTIC_PASSWORD
        value: "{{ restic_password }}"
      vars:
        restic_password: kali

    - name: Initialisiere das Backup-Repository
      win_shell: |
        restic -r sftp:{{ backup_user }}@{{ ansible_host }}:/windows init
      environment:
        RESTIC_PASSWORD: "{{ restic_password }}"
      vars:
        backup_user: rbackup

    - name: Führe ein Test-Backup durch
      win_shell: |
        restic -r sftp:{{ backup_user }}@{{ ansible_host }}:/windows backup C:\ --use-fs-snapshot
      environment:
        RESTIC_PASSWORD: "{{ restic_password }}"
      vars:
        backup_user: rbackup
