---
- name: Full System Backup
  hosts: all
  gather_facts: yes

  tasks:
    - name: Install Restic (Windows)
      win_chocolatey:
        name: restic
        state: present
      when: ansible_os_family == 'Windows'

    - name: Install Restic (Linux)
      apt:
        name: restic
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Execute Windows Backup
      win_command: |
        restic -r "\\{{ backup_server_ip }}\backups" backup C:\ 
        --password "{{ vault_restic_password }}" 
        --host "{{ inventory_hostname }}"
      args:
        stdin: "{{ vault_restic_password }}"
      when: ansible_os_family == 'Windows'

    - name: Execute Linux Backup
      command: |
        restic -r "sftp:{{ backup_user }}@{{ backup_server_ip }}:/backups" backup / 
        --password "{{ vault_restic_password }}" 
        --host "{{ inventory_hostname }}"
      args:
        stdin: "{{ vault_restic_password }}"
      when: ansible_os_family == 'Debian'