- name: Dynamic Wallpaper Synchronizer for Kali Linux
  hosts: linux
  gather_facts: yes
  vars:
    wallpaper_url: "https://images.unsplash.com/photo-1483982258113-b72862e6cff6?q=80&w=1740&auto=format&fit=crop"
    weather_api: "http://api.openweathermap.org/data/2.5/weather"
    api_key: "ddfb11805a9028aa945f65d181b4d6fb"
    quote_api: "https://zenquotes.io/api/random"
    download_path: "/tmp/wallpaper.jpg"
    location: "Berlin"  # 🌍 Wetter-Ort anpassen

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - feh
          - imagemagick
        state: present
      become: yes

    - name: Download wallpaper image
      ansible.builtin.get_url:
        url: "{{ wallpaper_url }}"
        dest: "{{ download_path }}"
        mode: "0644"

    - name: Fetch dynamic quote
      ansible.builtin.uri:
        url: "{{ quote_api }}"
        return_content: yes
      register: quote_response
      failed_when: quote_response.status != 200
      ignore_errors: true

    - name: Extract quote text
      set_fact:
        quote_text: "{{ quote_response.json[0]['q'] | default('No quote available') }}"

    - name: Fetch local weather
      ansible.builtin.uri:
        url: "{{ weather_api }}?q={{ location }}&appid={{ api_key }}&units=metric"
        return_content: yes
      register: weather_response
      failed_when: weather_response.status != 200
      ignore_errors: true

    - name: Extract weather description
      set_fact:
        weather_text: "{{ weather_response.json.weather[0].description | default('No weather data') }} | Temp: {{ weather_response.json.main.temp | default('N/A') }}°C"

    - name: Overlay text onto wallpaper
      ansible.builtin.command:
        argv:
          - convert
          - "{{ download_path }}"
          - -fill
          - white
          - -pointsize
          - "24"
          - -annotate
          - +10+50
          - "Quote: {{ quote_text }} | Weather: {{ weather_text }}"
          - "{{ download_path }}"
      changed_when: true

    - name: Set wallpaper using feh
      ansible.builtin.command:
        argv:
          - feh
          - "--bg-scale"
          - "{{ download_path }}"
      environment:
        DISPLAY: ":0"
        XAUTHORITY: "/home/{{ ansible_user }}/.Xauthority"
      changed_when: true

    - name: Ensure wallpaper is set on startup
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_user }}/.xsessionrc"
        line: "feh --bg-scale {{ download_path }}"
        create: yes
        state: present
      become: no
