- name: Dynamic Wallpaper Synchronizer
  hosts: all
  gather_facts: no
  vars:
    wallpaper_url: "https://imgur.com/z8KCBPz"
    weather_api: "http://api.openweathermap.org/data/2.5/weather"
    api_key: "ddfb11805a9028aa945f65d181b4d6fb"
    quote_api: "https://zenquotes.io/api/random"
    download_path: "C:\\Temp\\wallpaper.jpg"

  tasks:
    - name: Ensure download directory exists
      win_file:
        path: "C:\\Temp"
        state: directory

    - name: Fetch dynamic quote
      win_uri:
        url: "{{ quote_api }}"
        return_content: yes
      register: quote_response
      failed_when: false

    - name: Fetch local weather
      win_uri:
        url: "{{ weather_api }}?q=London&appid={{ api_key }}"
        return_content: yes
      register: weather_response
      failed_when: false

    - name: Download wallpaper image
      win_uri:
        url: "{{ wallpaper_url }}"
        dest: "{{ download_path }}"
        return_content: yes
      register: download_response
      failed_when: false

    - name: Apply wallpaper without modification
      win_shell: |
        RUNDLL32.EXE user32.dll, UpdatePerUserSystemParameters
      when: download_response is succeeded
