- name: Dynamic Wallpaper Synchronizer for Linux
  hosts: kali
  gather_facts: yes
  vars:
    wallpaper_url: "https://images.unsplash.com/photo-1483982258113-b72862e6cff6?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    weather_api: "http://api.openweathermap.org/data/2.5/weather"
    api_key: "ddfb11805a9028aa945f65d181b4d6fb"
    quote_api: "https://zenquotes.io/api/random"
    download_path: "/tmp/wallpaper.jpg"
    final_wallpaper_path: "/usr/share/backgrounds/wallpaper.jpg"

  tasks:
    - name: Ensure download directory exists
      file:
        path: "/tmp"
        state: directory

    - name: Fetch dynamic quote
      uri:
        url: "{{ quote_api }}"
        return_content: yes
      register: quote_response
      failed_when: false

    - name: Fetch local weather
      uri:
        url: "{{ weather_api }}?q=London&appid={{ api_key }}"
        return_content: yes
      register: weather_response
      failed_when: false

    - name: Download wallpaper image
      command: wget -O "{{ download_path }}" "{{ wallpaper_url }}"
      ignore_errors: yes

    - name: Verify downloaded image file
      shell: file "{{ download_path }}"
      register: verify_image
      failed_when: "'image data' not in verify_image.stdout"

    - name: Overlay quote and weather on the wallpaper
      command: >
        convert "{{ download_path }}"
        -pointsize 20 -fill white -annotate +10+20 "Quote: {{ quote_response.content.q }}"
        -pointsize 20 -fill white -annotate +10+50 "Weather: {{ weather_response.content.weather[0].description }}"
        "{{ final_wallpaper_path }}"
      when: quote_response.status == 200 and weather_response.status == 200

    - name: Apply the wallpaper
      shell: |
        gsettings set org.gnome.desktop.background picture-uri "file://{{ final_wallpaper_path }}"
      when: ansible_default_ipv4['address'] == "gnome"
