- name: Dynamic Wallpaper with Quote
  hosts: linux
  gather_facts: yes
  vars:
    wallpaper_url: "https://images.unsplash.com/photo-1483982258113-b72862e6cff6?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    quote_api: "https://zenquotes.io/api/random"
    download_path: "/tmp/wallpaper.jpg"
    final_wallpaper_path: "/usr/share/backgrounds/wallpaper.jpg"

  tasks:
    - name: Ensure download directory exists
      file:
        path: "/tmp"
        state: directory

    - name: Fetch dynamic quote
      uri:
        url: "{{ quote_api }}"
        return_content: yes
      register: quote_response
      failed_when: false

    - name: Debug quote response
      debug:
        var: quote_response

    - name: Download wallpaper image
      command: wget -O "{{ download_path }}" "{{ wallpaper_url }}"
      ignore_errors: yes

    - name: Verify downloaded image file
      shell: file "{{ download_path }}"
      register: verify_image
      failed_when: "'image data' not in verify_image.stdout"

    - name: Overlay quote on the wallpaper
      command: >
        convert "{{ download_path }}"
        -pointsize 40 -fill black -annotate +50+50 "Quote: {{ quote_response.json[0]['q'] | default('No quote available') }}"
        "{{ final_wallpaper_path }}"
      when: quote_response.status == 200

    - name: Apply the wallpaper
      shell: |
        gsettings set org.gnome.desktop.background picture-uri "file://{{ final_wallpaper_path }}"
      ignore_errors: yes
