---
- name: Minimal test playbook for Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Test connectivity to Windows PC
      win_ping:

    - name: Create a test directory
      win_file:
        path: C:\ansible_test
        state: directory

    - name: Create a test file in the directory
      win_file:
        path: C:\ansible_test\test_file.txt
        state: touch

    - name: Append a test message to the file
      win_shell: Add-Content -Path C:\ansible_test\test_file.txt -Value "Ansible test successful!"
