---
- name: Automate and Hardening Windows Server
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Test connectivity to Windows
      win_ping:

    - name: Gather system facts (for inventory)
      setup:

    - name: Install Google Chrome using Chocolatey
      community.windows.win_chocolatey:
        name: googlechrome
        state: present

    - name: Install critical and security updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        state: installed
      register: update_result

    - name: Reboot system if updates require it
      win_reboot:
        when: update_result.reboot_required

    - name: Disable Windows Defender Real-Time Protection (if needed for specific cases)
      win_service:
        name: WinDefend
        state: stopped
        start_mode: disabled

    - name: Set Windows time zone to UTC
      win_timezone:
        timezone: UTC

    - name: Enable Windows Defender Antivirus
      win_service:
        name: WinDefend
        state: started
        start_mode: auto

    - name: Disable unused ports (disable SMBv1, for example)
      win_feature:
        name: FS-SMB1
        state: absent

    - name: Enable Windows firewall and configure inbound rules
      win_firewall_rule:
        name: "Allow SSH"
        localport: 22
        protocol: TCP
        action: allow
        enable: yes

    - name: Install and configure IIS Web Server
      win_feature:
        name: Web-Server
        state: present

    - name: Create directory structure for IIS website
      win_file:
        path: C:\inetpub\wwwroot\mywebsite
        state: directory

    - name: Deploy custom website files (example)
      win_copy:
        src: /path/to/local/website/files/
        dest: C:\inetpub\wwwroot\mywebsite\
        remote_src: no

    - name: Restart IIS to apply changes
      win_service:
        name: W3SVC
        state: restarted

    - name: Enable and configure SNMP service
      win_feature:
        name: SNMP-Service
        state: present
      register: snmp_status

    - name: Start SNMP service if installed
      win_service:
        name: SNMP
        state: started
        start_mode: auto
      when: snmp_status.changed

    - name: Set up logging for Windows updates
      win_eventlog:
        name: Application
        source: Microsoft-Windows-UpdateAgent
        type: Information
        event_id: 19
        message: "Successfully installed updates"

    - name: Send notification email upon success
      mail:
        host: smtp.yourserver.com
        port: 25
        to: "admin@example.com"
        subject: "Windows Server Update Complete"
        body: "The playbook has completed successfully. All updates and tasks were applied."
