---
- name: Backup Windows PCs to Backup Server
  hosts: all
  gather_facts: yes
  vars:
    backup_server: "\\\\192.168.100.137\\Backup"
    backup_user: "backupuser"
    backup_password: "kali"
    backup_archive: "Backup-{{ ansible_hostname }}-{{ ansible_date_time.date }}.zip"

  tasks:
    - name: Test connectivity
      win_ping:

    - name: Create temp directory if it does not exist
      win_file:
        path: C:\\temp
        state: directory

    - name: Map network drive to backup server
      win_shell: |
        net use Z: {{ backup_server }} /user:{{ backup_user }} {{ backup_password }}

    - name: Compress user directories into ZIP files
      win_shell: |
        Compress-Archive -Path "$env:USERPROFILE\*" -DestinationPath "C:\\temp\\{{ backup_archive }}" -Force

    - name: Verify ZIP archive exists
      win_stat:
        path: "C:\\temp\\{{ backup_archive }}"
      register: archive_check

    - name: Fail if ZIP archive is not created
      fail:
        msg: "Backup archive was not created!"
      when: not archive_check.stat.exists

    - name: Copy ZIP archive to backup server
      win_shell: |
        Copy-Item -Path "C:\\temp\\{{ backup_archive }}" -Destination "{{ backup_server }}" -Force
      args:
        executable: powershell

    - name: Clean up local temp files
      win_file:
        path: "C:\\temp\\{{ backup_archive }}"
        state: absent

    - name: Unmap network drive
      win_shell: |
        net use Z: /delete /y

