---
- name: Cleanup and Prune Old Backups
  hosts: localhost
  gather_facts: no
  vars:
    restic_password: "kali"
    backup_repo: "rest:http://192.168.72.131:8000/repo"  # Beispiel: REST-Server oder NFS-Mount

  tasks:
    - name: Create .restic.env file with password
      copy:
        content: "export RESTIC_PASSWORD={{ restic_password }}"
        dest: ~/.restic.env
        mode: '0600'

    - name: Source Restic environment variables
      shell: |
        source ~/.restic.env
        echo $RESTIC_PASSWORD
      register: restic_env
      changed_when: false

    - name: Forget old snapshots
      shell: |
        source ~/.restic.env
        restic -r {{ backup_repo }} forget --keep-last 7 --keep-daily 30 --keep-weekly 12
      register: forget_result
      failed_when: forget_result.rc != 0

    - name: Prune repository
      shell: |
        source ~/.restic.env
        restic -r {{ backup_repo }} prune
      register: prune_result
      failed_when: prune_result.rc != 0

    - name: Debug cleanup results
      debug:
        msg: "Snapshots forgotten: {{ forget_result.stdout_lines }}\nPrune results: {{ prune_result.stdout_lines }}"