---
- name: Backup Linux Hosts
  hosts: linux
  gather_facts: yes
  vars:
    restic_password: "kali"
    backup_repo: "/mnt/backup/repo"  # Pfad zum Restic-Repository
    backup_paths:
      - /home
      - /etc
      - /var/log

  tasks:
    - name: Ensure Restic is installed (Debian/Ubuntu)
      apt:
        name: restic
        state: present
      when: ansible_os_family == "Debian"
      become: yes

    - name: Ensure Restic is installed (RHEL/CentOS)
      yum:
        name: restic
        state: present
      when: ansible_os_family == "RedHat"
      become: yes

    - name: Create .restic.env file with password
      copy:
        content: "export RESTIC_PASSWORD={{ restic_password }}"
        dest: ~/.restic.env
        mode: '0600'
      become: yes

    - name: Source Restic environment variables
      shell: |
        source ~/.restic.env
        echo $RESTIC_PASSWORD
      register: restic_env
      changed_when: false
      become: yes

    - name: Ensure backup repository directory exists
      file:
        path: "{{ backup_repo }}"
        state: directory
        owner: root
        group: root
        mode: '0700'
      become: yes

    - name: Initialize Restic repository if not already initialized
      shell: |
        set -a
        source ~/.restic.env
        set +a
        restic -r {{ backup_repo }} snapshots || restic -r {{ backup_repo }} init
      args:
        executable: /bin/bash  # Verwenden Sie explizit Bash
      become: yes

    - name: Run backups for specified paths
      shell: |
        set -a
        source ~/.restic.env
        set +a
        restic -r {{ backup_repo }} backup {{ item }} --verbose
      args:
        executable: /bin/bash  # Verwenden Sie explizit Bash
      loop: "{{ backup_paths }}"
      become: yes

    - name: Verify backups were created
      shell: |
        set -a
        source ~/.restic.env
        set +a
        restic -r {{ backup_repo }} snapshots
      args:
        executable: /bin/bash  # Verwenden Sie explizit Bash
      register: snapshot_list
      failed_when: snapshot_list.rc != 0
      become: yes

    - name: Debug output of snapshots
      debug:
        msg: "{{ snapshot_list.stdout_lines }}"