---
- name: Perform Incremental Backups with BorgBackup
  hosts: linux_hosts
  become: yes
  vars:
    backup_server_ip: "192.168.72.131"
    backup_repo_path: "ssh://backuper@{{ backup_server_ip }}/mnt/backup/linux/{{ ansible_hostname }}"
    borg_passphrase: "your_secure_password"  # Ändern Sie dies in ein sicheres Passwort!
    exclude_files:
      - /dev/
      - /proc/
      - /sys/
      - /tmp/
      - /run/
      - /mnt/
      - /media/
      - /lost+found

  tasks:
    - name: Ensure BorgBackup is installed on client
      apt:
        name: borgbackup
        state: present
      tags: install

    - name: Create SSH key if it does not exist
      user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      when: not lookup('file', '~/.ssh/id_rsa.pub', errors='ignore')
      tags: setup

    - name: Copy public SSH key to backup server
      authorized_key:
        user: backuper
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      delegate_to: "{{ backup_server_ip }}"
      become: yes
      become_user: backuper
      tags: setup

    - name: Perform incremental backup
      command: >
        borg create
        --compression lz4
        --exclude {{ item }}
        {{ backup_repo_path }}::{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}
        /
      loop: "{{ exclude_files }}"
      environment:
        BORG_PASSPHRASE: "{{ borg_passphrase }}"
      tags: backup