- name: Backup-System für Linux-Hosts
  hosts: linux
  become: yes
  vars:
    backup_server: "192.168.72.132"
    backup_dir: "/backup"
    rsync_options: "-avz --exclude /proc --exclude /sys --exclude /tmp --exclude /run --exclude /mnt --exclude /media --exclude /backup --exclude /lost+found"

  tasks:
    - name: Erstelle Backup-Verzeichnis auf dem Host
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: backuper
        group: backuper

    - name: Synchronisiere Dateien mit dem Backup-Server
      ansible.builtin.synchronize:
        src: "/"
        dest: "backuper@{{ backup_server }}:{{ backup_dir }}/{{ inventory_hostname }}/"
        rsync_opts: "{{ rsync_options }}"
        ssh_args: "-o PubkeyAuthentication=no -o PasswordAuthentication=yes"
      vars:
        ansible_ssh_user: backuper
        ansible_ssh_pass: kali