---
- name: Fully Automated Backup Setup for Linux Clients with BorgBackup
  hosts: linux
  become: yes
  vars:
    backup_server_ip: "192.168.72.131"  # IP des Backup-Servers
    backup_user: "backuper"             # Benutzername auf dem Backup-Server
    backup_repo_path: "ssh://{{ backup_user }}@{{ backup_server_ip }}/mnt/backup/linux/{{ ansible_hostname }}"
    borg_passphrase: "kali"  # Ändern Sie dies in ein sicheres Passwort!
    exclude_files:
      - /dev/
      - /proc/
      - /sys/
      - /tmp/
      - /run/
      - /mnt/
      - /media/
      - /lost+found

  tasks:

    # --- GRUPPE 1: SICHERSTELLEN, DASS ANSIBLE MODULE FUNKTIONIEREN ---
    - name: Ensure python3-apt is installed
      raw: apt update && apt install -y python3-apt
      when: ansible_distribution == "Ubuntu"

    # --- GRUPPE 2: INSTALLATION VON BORGBACKUP ---
    - name: Install BorgBackup on the client
      apt:
        name: borgbackup
        state: present

    # --- GRUPPE 3: EINRICHTUNG PASSWORDFREIEN SSH-ZUGRIFFS ---
    - name: Generate SSH key pair if it does not exist
      user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
      when: not lookup('file', '~/.ssh/id_rsa.pub', errors='ignore')

    - name: Copy public SSH key to backup server
      authorized_key:
        user: "{{ backup_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      delegate_to: "{{ backup_server_ip }}"
      become: yes
      become_user: "{{ backup_user }}"

    # --- GRUPPE 4: BACKUP-AUSFÜHRUNG ---
    - name: Perform incremental backup
      command: >
        borg create
        --compression lz4
        --exclude {{ item }}
        {{ backup_repo_path }}::{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}
        /
      loop: "{{ exclude_files }}"
      environment:
        BORG_PASSPHRASE: "{{ borg_passphrase }}"