---
- name: Backup Linux-Hosts mit BorgBackup
  hosts: linux
  become: yes
  vars:
    backup_server_ip: "192.168.72.128"
    backup_repo_path: "/var/backups/borg"
    backup_user: "backuper"
    backup_password: "kali"

  tasks:
    - name: Installiere notwendige Pakete
      raw: |
        apt-get update
        apt-get install -y python3 python3-apt sshpass borgbackup
        ln -sf /usr/bin/python3 /usr/bin/python

    - name: Backup-Archiv erstellen
      command: >
        borg create --stats {{ backup_user }}@{{ backup_server_ip }}:{{ backup_repo_path }}::backup-{now:%Y-%m-%d} /home
      environment:
        BORG_RSH: "sshpass -p {{ backup_password }} ssh -o StrictHostKeyChecking=no"

    - name: Alte Backups bereinigen
      command: >
        borg prune --list --keep-daily=7 --keep-weekly=4 --keep-monthly=6 {{ backup_user }}@{{ backup_server_ip }}:{{ backup_repo_path }}
      environment:
        BORG_RSH: "sshpass -p {{ backup_password }} ssh -o StrictHostKeyChecking=no"