---
- name: Backup Windows Hosts
  hosts: windows
  gather_facts: no
  vars:
    restic_password: "kali"
    backup_repo: "\\\\192.168.72.131\\backup"
    backup_paths:
      - 'C:\Users\ansible'
      - 'C:\Program Files'  # Korrigierter Pfad für englische Systeme

  tasks:
    - name: Map network drive
      win_shell: |
        net use "{{ backup_repo }}" /user:backuper kali /persistent:yes
      args:
        executable: cmd
      register: net_use
      failed_when: net_use.rc != 0 and 'error 85' not in net_use.stderr

    - name: Validate repository connection
      win_shell: |
        restic -r "{{ backup_repo }}" --password "{{ restic_password }}" snapshots
      args:
        executable: cmd
      register: repo_check
      ignore_errors: yes
      changed_when: false

    - name: Force repository initialization
      win_shell: |
        restic -r "{{ backup_repo }}" --password "{{ restic_password }}" init
      args:
        executable: cmd
      when: repo_check.rc != 0

    - name: Run backups with verification
      block:
        - name: Execute backup
          win_shell: |
            restic backup "{{ item }}" --repo "{{ backup_repo }}" --password "{{ restic_password }}" --verbose
          args:
            executable: cmd
          loop: "{{ backup_paths }}"
          register: backup_results

        - name: Verify backup
          win_shell: |
            restic -r "{{ backup_repo }}" --password "{{ restic_password }}" snapshots
          args:
            executable: cmd
          register: snapshots

        - name: Show backup proof
          debug:
            var: snapshots.stdout_lines

      rescue:
        - name: Capture backup error
          debug:
            msg: "BACKUP FAILED: {{ backup_results.results | map(attribute='stderr') | list }}"