---
- name: Backup Windows Hosts
  hosts: windows
  gather_facts: no
  vars:
    restic_password: "kali"
    backup_repo: "\\\\192.168.72.131\\mnt\\backup\\repo"
    backup_paths:
      - C:\Benutzer
      - C:\Programme
  tasks:
    - name: Install Chocolatey if not already installed
      win_shell: |
        if (-not (Test-Path "$env:ProgramData\Chocolatey")) {
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        }
      args:
        creates: "$env:ProgramData\Chocolatey"

    - name: Install Restic using Chocolatey
      win_shell: |
        choco install restic -y --force

    - name: Add Restic to PATH
      win_path:
        elements:
          - "C:\\ProgramData\\chocolatey\\bin"
        state: present

    - name: Run Restic Backup
      win_shell: |
        $env:RESTIC_PASSWORD = "{{ restic_password }}"
        restic backup {{ item }} --repo {{ backup_repo }}
      loop: "{{ backup_paths }}"