---
- name: Backup Windows Hosts
  hosts: windows
  gather_facts: no
  vars:
    restic_password: "kali"
    backup_repo: "\\\\192.168.72.131\\mnt\\backup\\repo"
    restic_url: "https://github.com/restic/restic/releases/download/v0.15.1/restic_0.15.1_windows_amd64.zip"
    restic_install_path: "C:\\Programme\\Restic"
    backup_paths:
      - C:\Benutzer
      - C:\Programme
  tasks:
    - name: Create Restic installation directory
      win_file:
        path: "{{ restic_install_path }}"
        state: directory

    - name: Download Restic binary
      win_get_url:
        url: "{{ restic_url }}"
        dest: "{{ restic_install_path }}\\restic.zip"

    - name: Extract Restic binary using PowerShell
      win_shell: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::ExtractToDirectory("{{ restic_install_path }}\\restic.zip", "{{ restic_install_path }}")

    - name: Add Restic to PATH
      win_path:
        elements:
          - "{{ restic_install_path }}"
        state: present

    - name: Run Restic Backup
      win_shell: |
        $env:RESTIC_PASSWORD = "{{ restic_password }}"
        restic backup {{ item }} --repo {{ backup_repo }}
      loop: "{{ backup_paths }}"