---
- name: Windows Backup mit Restic
  hosts: windows
  gather_facts: no
  vars:
    restic_repo: "\\\\192.168.72.131\\backup"
    restic_password: "{{ restic_vault_password }}"
    backup_paths:
      - C:\Users\ansible
      - C:\Programme

  tasks:
    - name: Chocolatey installieren
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      args:
        creates: "C:\\ProgramData\\Chocolatey"
      when: not ansible_check_mode

    - name: Chocolatey PATH hinzuf체gen
      win_path:
        elements:
          - C:\ProgramData\chocolatey\bin
        state: present

    - name: Restic installieren
      win_shell: |
        choco install restic -y --force
      args:
        executable: cmd

    - name: Netzwerkfreigabe verbinden
      win_shell: |
        net use {{ restic_repo }} /user:backuper "{{ smb_password }}" /persistent:no
      args:
        executable: cmd
      register: net_use
      failed_when: net_use.rc not in [0, 2]

    - name: Repository initialisieren
      win_shell: |
        restic -r "{{ restic_repo }}" init --password "{{ restic_password }}"
      args:
        executable: cmd
      register: init_repo
      changed_when: "'already initialized' not in init_repo.stderr"

    - name: Backup durchf체hren
      win_shell: |
        restic backup "{{ item }}" --repo "{{ restic_repo }}" --password "{{ restic_password }}" --verbose
      loop: "{{ backup_paths }}"
      args:
        executable: cmd
      register: backup_results

    # AB HIER DIE CHECKS
    - name: Backup-Ergebnisse validieren
      debug:
        msg: |
          Backup von {{ item.item }}:
          - Exit Code: {{ item.rc }}
          - Output: {{ item.stdout_lines }}
          - Fehler: {{ item.stderr_lines if item.rc != 0 else 'Keine' }}
      loop: "{{ backup_results.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Snapshots auflisten
      win_shell: |
        restic -r "{{ restic_repo }}" snapshots --password "{{ restic_password }}"
      args:
        executable: cmd
      register: snapshots
      changed_when: false

    - name: Snapshots anzeigen
      debug:
        msg: "{{ snapshots.stdout_lines }}"

    - name: Repository-Integrit채t pr체fen
      win_shell: |
        restic -r "{{ restic_repo }}" check --password "{{ restic_password }}"
      args:
        executable: cmd
      register: repo_check
      changed_when: false

    - name: Check-Ergebnis
      debug:
        msg: "{{ repo_check.stdout_lines }}"