---
- name: Windows Backup mit Restic
  hosts: windows
  gather_facts: no
  vars:
    restic_repo: "\\\\192.168.72.131\\backup"
    restic_password: "{{ restic_vault_password }}"
    backup_paths:
      - C:\Users\ansible
      - C:\Programme

  tasks:
    - name: Chocolatey installieren
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      args:
        creates: "C:\\ProgramData\\Chocolatey"
      when: not ansible_check_mode

    - name: Chocolatey PATH hinzufügen
      win_path:
        elements:
          - C:\ProgramData\chocolatey\bin
        state: present

    # Geänderter Task mit win_package
    - name: Restic installieren
      win_package:
        name: restic
        path: https://github.com/restic/restic/releases/download/v0.16.0/restic_0.16.0_windows_amd64.zip
        product_id: restic
        arguments: /S
      when: not ansible_check_mode

    - name: Netzwerkfreigabe verbinden
      win_shell: |
        net use {{ restic_repo }} /user:backuper "{{ smb_password }}" /persistent:no
      args:
        executable: cmd
      register: net_use
      failed_when: net_use.rc not in [0, 2]

    - name: Repository initialisieren
      win_shell: |
        restic -r "{{ restic_repo }}" init --password "{{ restic_password }}"
      args:
        executable: cmd
      register: init_repo
      changed_when: "'already initialized' not in init_repo.stderr"

    - name: Backup durchführen
      win_shell: |
        restic backup "{{ item }}" --repo "{{ restic_repo }}" --password "{{ restic_password }}" --verbose
      loop: "{{ backup_paths }}"
      args:
        executable: cmd
      register: backup_results